# Generated by Django 4.2 on 2023-05-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatin',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
